### ISSUE TITLE
[Issue/Feedback/Question] For ver 1.0.13

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_MattyFixes#1]
same as topic, but i can simply disable that

**Comment by CoolLKKPS** [comment]
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:0)
MattyFixes.Patches.NamePatches.PostUpdate (StartOfRound __instance) (at <3979166800c74ff39ae670523e1ac9af>:0)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::LateUpdate>(StartOfRound)

**Comment by CoolLKKPS** [comment]
v1.0.1 with namefix disabled
ok u also mess up the monitor, now the monitor will show less player after u host the lobby for too long, and we definitely activate the radar

**Comment by CoolLKKPS** [comment]
here's the log, with 1.0.1

**Comment by CoolLKKPS** [comment]
@mattymatty97 delete after u see it
[LogOutput.log](https://github.com/mattymatty97/LTC_MattyFixes/files/14662721/LogOutput.log)

**Comment by CoolLKKPS** [comment]
uh i will roll back to 0.0.3 until u fix that, might be conflict issues

**Comment by CoolLKKPS** [comment]
@mattymatty97 another question about level patch, does this conflict with Fix_XP_Divide_By_Zero_Error made by Simplexity
> note AntiCheat made by chuxiaaaa are also fix xp divide by zero by his own

**Comment by mattymatty97** [comment]
uhh i need to check for them, but should be compatible as what i'm doing is just capping the max level when sending it to other clients 🤔

**Comment by mattymatty97** [comment]
ok no it's another thing entirely, this namefix is intended to prevent people with more xp than Boss to rollback to intern tag

**Comment by CoolLKKPS** [comment]
nice, and btw
i will convert this issue ticket to be a thread since i use ur mods very often

**Comment by CoolLKKPS** [comment]
@mattymatty97 can u fix the "toomanysuit" update error when the host using lobby control to hot load a savefile?

**Comment by mattymatty97** [comment]
i can try and look into it, but it may be something they have to fix on their side

**Comment by CoolLKKPS** [comment]
and namefix not work in spectator mode

**Comment by mattymatty97** [comment]
> i can try and look into it, but it may be something they have to fix on their side

can confirm is a change they have to do on their side:
instead of  initializing in a postfix of `StartOfRound.Start` they should use a postfix of `StartOfRound.LoadUnlockables`
will change almost nothing on their side while making it compatible with any mod that does reload the furniture w/o quitting the game

**Comment by CoolLKKPS** [comment]
@mattymatty97 sadly i cannot use discord so i cannot contact that author, but uh can u help me? or can u make a fork version to fix those issues?

**Comment by CoolLKKPS** [comment]
also have error log when quit to main menu btw:
[17:02:27.5286127] [Error  : Unity Log] NullReferenceException
Stack trace:
TooManySuits.PluginLoader.DisplaySuits () (at <434b74dca9584b6891fed93d3e2a47a3>:0)
(wrapper dynamic-method) TooManySuits.PluginLoader.DMD<TooManySuits.PluginLoader::Update>(TooManySuits.PluginLoader)

[17:02:27.5286127] [Error  : Unity Log] NullReferenceException
Stack trace:
TooManySuits.PluginLoader.DisplaySuits () (at <434b74dca9584b6891fed93d3e2a47a3>:0)
(wrapper dynamic-method) TooManySuits.PluginLoader.DMD<TooManySuits.PluginLoader::Update>(TooManySuits.PluginLoader)

timezone: utc+8 but log timezone is utc time

**Comment by mattymatty97** [comment]
modder is not on the modding discord,
and the mod has not been updated in 3 months... it probably will stop working after v50

**Comment by CoolLKKPS** [comment]
uh nope, still active!

**Comment by CoolLKKPS** [comment]
and this issues fixed! i have to say wohoo finally!
