### ISSUE TITLE
[Bug/Issue] ItemClipping lower on spawn than on drop

### ISSUE THREAD

**Issue by MathiusXII** [mattymatty97/LTC_MattyFixes#10]
When items spawn in they are lower to the ground than when you drop them. 
I've had keys look fine when dropped, but they spawn slightly underground. (enough to still grab and scan them but they're not visible)

**Comment by MathiusXII** [comment]
Looks like reloading the save also drops any items on the ship to that lower point too

**Comment by mattymatty97** [comment]
beein fixed in Experimental. will close for now.
