### ISSUE TITLE
[Request] ItemClipping save loading blacklist

### ISSUE THREAD

**Issue by MathiusXII** [mattymatty97/LTC_MattyFixes#11]
Some items like LethalThings' darts and LethalSnap's pictures can be attached to walls and fall to the ground on loading a save.

**Comment by mattymatty97** [comment]
that's vanilla behaviour, all items will attempt to fall to the ground on load.
it's something that has to be fixed on LethalThings side

**Comment by MathiusXII** [comment]
Just did some testing with minimal mods.

Without MattyFixes, the darts are stuck sideways into walls. They do seem pretty glitchy in how they save, but they are always stuck in a wall. Not necessarily the correct wall though... LethalSnaps pictures didn't move at all.

After activating MattyFixes, all darts are stuck in the ground tail facing straight up. LethalSnaps pictures surprisingly stayed put this time. Maybe I had some other mod conflict for that one?

EDIT
Ok just tested with my modpack again and LethalSnaps pictures stayed on the wall there this time too... guess they're fine now? shrug
