### ISSUE TITLE
[Conflict] GeneralImprovement's FixItemsLoadingSameRotation

### ISSUE THREAD

**Issue by MathiusXII** [mattymatty97/LTC_MattyFixes#12]
Doesn't save

Should I mention this to Shaosil instead?

**Comment by mattymatty97** [comment]
this i a known incompatibility, as both mods are trying to change the item rotation on spawn.
disable `rotate_on_spawn` if you want to use GI rotation

**Comment by MathiusXII** [comment]
Ooh ok by "fix rotation of some items while dropped" I thought you meant the way you changed the rotations of some items such as the V-type engine and green flashlight. Thanks

**Comment by mattymatty97** [comment]
there are multiple layers of the same fix. the specific config settings i just mentioned. handles the rotation of newly spawned items. while the `enabled` one on the same section. controls the fix as a whole
