### ISSUE TITLE
[Suggestion] LCGoldScrap item clipping fix support

### ISSUE THREAD

**Issue by dopadream** [mattymatty97/LTC_MattyFixes#14]
LCGoldScrap adds gold variations of vanilla scraps, I was wondering if it would be possible/not too much trouble for the item rotation/clipping fix from this mod to be applied to the items from that. They all appear to use the same offset/rotations as vanilla items

https://thunderstore.io/c/lethal-company/p/SimonTendo/LCGoldScrapMod/

**Comment by mattymatty97** [comment]
i do plan on having the rotations, configurable. but at the moment only vanilla items that were mapped by ItemClippingFix have a modified rotation.

**Comment by mattymatty97** [comment]
all items have now a entry in config to customize rotation

**Comment by dopadream** [comment]
Hi, for some reason it generates entries for custom items, but after restarting my game the entry for this one keeps deleting itself. https://thunderstore.io/c/lethal-company/p/Entity378/Motion_Tracker_V2/ Are you able to reproduce this?
