### ISSUE TITLE
[Bug] Company cruiser issues & improvements

### ISSUE THREAD

**Issue by zndrmn** [mattymatty97/LTC_MattyFixes#15]
Here's a list of the bugs that I've been experiencing:

~~Dropping items in the cruiser while crouched will cause them to fall through.~~
~~The clipboard manual doesn't spawn with the cruiser, but spawns inside of the ship after a cycle.~~
~~Items can no longer be placed on the top shelf~~
~~Some items float above the front bench/shelf and some go below it, making it impossible to grab.~~
~~Items can sometimes clip into the cruiser walls after being placed on a shelf making them impossible to grab.~~

**Comment by zndrmn** [comment]
(Using the experimental release) I will cross out issues that have been fixed.

~~Most items aren't aligned with the cruiser when placed on a shelf~~
~~Dropping items while looking forward will cause the items to fall through the floor of the cruiser (in video)~~
~~Dropping items while looking up will cause them to float semi-inside of the ceiling (in image/video: engine, cog)~~
~~Items placed on the bottom shelves will float (in image: gold bar)~~
~~Items placed on the bench shelf will float (in image: golden cup, and shovel)~~
~~Items placed on the top shelves will clip into the wall, causing them to be impossible to pick up (in image: screw, and clown horn)~~

<details closed>

![1966720_20240709195530_1](https://github.com/mattymatty97/LTC_MattyFixes/assets/77690119/a9f8f6e4-eb71-4ee1-b22e-62011ab31f8d)

<summary>fixed issues that had images/videos demonstrating them</summary>

https://github.com/mattymatty97/LTC_MattyFixes/assets/77690119/21e447ac-2d73-4518-b205-8a3d387140f7

https://github.com/mattymatty97/LTC_MattyFixes/assets/77690119/cd1d2505-cabb-466b-b232-a725f706a219

</details>

**Comment by zndrmn** [comment]
It seems like quite a few items float now with the rewrite (I am not sure if this was always the case for the cog but I know for sure the engine used to be flush with the ground)

![1966720_20240709203034_1](https://github.com/mattymatty97/LTC_MattyFixes/assets/77690119/084a41c1-d6fc-45a2-b794-080d0989aefc)

**Comment by zndrmn** [comment]
After going back into orbit, exiting, and reloading the save caused quite a few items to go missing, and with changed positions
The shovel was recovered (it got teleported at my feet after the reload)

![1966720_20240709203846_1](https://github.com/mattymatty97/LTC_MattyFixes/assets/77690119/653a175c-f96e-4f33-bf3b-50132fb9b562)

**Comment by mattymatty97** [comment]
i'm attempting a big rewrite for v56 compatibility so a lot of things will break during the Experimental cycle. i'll try to fix stuff one by one.
thanks for your reports

**Comment by zndrmn** [comment]
A rather funny issue occurs with the latest build/version haha

https://github.com/user-attachments/assets/9f37d414-bbe9-4fe3-a7cf-7965ce73de62

Seems like it happens with two-handed items as well

https://github.com/user-attachments/assets/7105fc31-25b9-41b0-bfdd-52ee76cd20ed

**Comment by mattymatty97** [comment]
yeah the object placement "Vertical Offset" is quite broken in v1.1.5 😅

**Comment by mattymatty97** [comment]
a lot of fixes have been included in v1.1.6 and now in v1.1.7 i suggest to use the new config defaults and check the new versions

**Comment by zndrmn** [comment]
Alright I'll do some testing

**Comment by zndrmn** [comment]
Seems like everything works really well now!

The only big issue that I'm having now is that two-handed items have a tendency to fall through the cruiser when dropped.
This mostly happens when you're looking slightly up/straight ahead.

Oh and if you look all the way up you can place items kinda in the ceiling
I have no clue how the item dropping works for the cruiser but it seems like the box for the items is shifted down enough to where you're able to place items ontop of the invisible box.
Two-handed Items also clip into the floor quite a bit as well (mainly the large axle/cog)

It would also be nice if placed down items would auto-rotate themselves to better fit on the shelf they were placed on so that you don't have to get lucky with the random rotation the item was originally given.
(you can just place the item down in the cruiser and take it out of the cruiser and drop it on the floor again to change the rotation of the item)

![1966720_20240714180938_1](https://github.com/user-attachments/assets/798a8b60-5962-4e70-8036-22e497a22f0c)

**Comment by zndrmn** [comment]
Picking up items in the cruiser after it has changed angles/rotation will cause those items to keep the original angles/rotation causing them to be misaligned with the cruiser

For some reason the weed killer (there might be more items that do this) seem to ignore the cruiser's angle/rotation altogether

![1966720_20240714182714_1](https://github.com/user-attachments/assets/2d2af5c4-f9ab-464c-b9bf-ba55743da276)

**Comment by mattymatty97** [comment]
a new update has been released, that removes the weird ability to "stick" items to the cruiser wall/ceiling

and also correctly applies the offset to prevent dropped items from clipping.

it's not widely known but the rotation an item has when placed on a surface ( cupboard / cruiser shelves ) is exactly the rotation the item had when you picked it up

best way to chose it is to drop it on the floor until it's rotated as you want and then pick it up and place it

**Comment by mattymatty97** [comment]
i might make a mod to allow placing the objects always in the same rotation but it would require for everybody to install it as vanilla does not sync rotation :/

**Comment by zndrmn** [comment]
> it's not widely known but the rotation an item has when placed on a surface ( cupboard / cruiser shelves ) is exactly the rotation the item had when you picked it up
>
>best way to chose it is to drop it on the floor until it's rotated as you want and then pick it up and place it

Yee I know about that.

>i might make a mod to allow placing the objects always in the same rotation but it would require for everybody to install it as vanilla does not sync rotation :/

Wouldn't that just make items never rotate? I actually don't really mind the random rotation mainly because you're able to change the rotation whenever. The no item rotation thing would make things look kinda weird imo (if it's some kind of global thing)

**Comment by mattymatty97** [comment]
the options for the rotation thing are two:
- rotate everything to be always aligned with the surface it is being placed on 
- rotate it to be rotated perpendicular to the direction the player is looking at

in both cases the rotation would be changed only when you are placing items on a kind of shelf and not when dropping items

**Comment by mattymatty97** [comment]
this is is by no means a declaration of "i'll do it" just discussing how a theoretical one might be done

**Comment by zndrmn** [comment]
> in both cases the rotation would be changed only when you are placing items on a kind of shelf and not when dropping items

Ahh that makes a lot more sense.

> this is is by no means a declaration of "i'll do it" just discussing how a theoretical one might be done

Mhm 👍 

oh yeah also the item dropping is very reliable now!
