### ISSUE TITLE
Each time the item is loaded, it will shift upwards by a certain distance

### ISSUE THREAD

**Issue by NakiriFox** [mattymatty97/LTC_MattyFixes#19]
I'm sure it's caused by this mod, version is "Matty_Fixes_Experimental-1.1.6"

**Comment by NakiriFox** [comment]
![Uploading 9d991441-8d27-41b2-9868-23121859d5fc.png…]()

**Comment by NakiriFox** [comment]
![Uploading 9d991441-8d27-41b2-9868-23121859d5fc.png…]()

**Comment by NakiriFox** [comment]
![mattyfixes](https://github.com/user-attachments/assets/b8ff167c-b837-4d5c-a202-d64ba9185d98)

**Comment by NakiriFox** [comment]
config settings are default

**Comment by NakiriFox** [comment]
![a237c39f-eff4-4145-8e5e-e347c124c5cb](https://github.com/user-attachments/assets/5a883593-407f-4c24-8113-25d76f41e310)
There is no such issue when using the Matty_Fixes-1.0.21.

**Comment by mattymatty97** [comment]
are you using other mods that "fix Cupboard"? eg: GI

**Comment by NakiriFox** [comment]
I forgot to mention that the experimental-1.1.6 version caused this problem :(
I install the GeneralImprovements-1.3.0, which of its settings will conflict with this mod

**Comment by mattymatty97** [comment]
![immagine](https://github.com/user-attachments/assets/12595293-a597-47ca-8000-cfed7d8fb17a)
`FixItemsFallingThrough` needs to be set to false.

their solution prevents any item from falling.

if you instead want to use GI setting then set `OutOfBounds.vertical_offset` to 0 in MattyFixes config

**Comment by NakiriFox** [comment]
thank you :)
i will use the MF settings
