### ISSUE TITLE
`NameFixes`Error

### ISSUE THREAD

**Issue by cangming99** [mattymatty97/LTC_MattyFixes#2]
If I enable `NameFixes`, I will get the following error log after I create the host:
```
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
MoreEmotes.Patch.EmotePatch.UpdatePrefix (GameNetcodeStuff.PlayerControllerB __instance) (at <e152e1967b684dcc9ff55d637143b2c4>:IL_0021)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)
```

**Comment by cangming99** [comment]
When I disable NameFixes, everything returns to normal.

**Comment by mattymatty97** [comment]
name fix is experimental and will probably be rewritten multiple times in the future
v1.0.8 should hopefully solve most of the issues that come from it

**Comment by mattymatty97** [comment]
seems to be fixed on 1.0.9+

**Comment by Lcinit** [comment]
I also experienced this error while using your LobbyControl v2.3.4.

**Comment by mattymatty97** [comment]
LobbyControl poast v2.3.0 does not even have the NameFix stuff anymore 🤔
