### ISSUE TITLE
[Bug] Masks fly into outer space

### ISSUE THREAD

**Issue by broken-usb** [mattymatty97/LTC_MattyFixes#20]
The option to manually offset the masks seems to cause them to literally fly upwards once you drop one, this doesn't happen if you play solo but if you play with other players on your server the bug will happen, happens both when being the Host or when being a Client. Setting the manual offset to nothing solves this tho.

Oh and keys spawn sideways on the frist day whenever joining a new lobby or a save file, they go back to spawning normally on the second day(by spawning keys i mean the ones that naturally spawn inside of the facility).

Modpack code: `0190c5d7-fd81-dc10-ed55-790ab616a5f5`

**Comment by mattymatty97** [comment]
i'll need some verbose logs to debug this.

to turn on verbose mode there is a setting in the config file under the [Debug] section

**Comment by broken-usb** [comment]
Joined a random lobby and picked up a mask that was on the ship's floor, after dropping it flew away going through the ship's ceiling.
[LogOutput.log](https://github.com/user-attachments/files/16321469/LogOutput.log)
I added a few more mods to the modpack during these 2 days but i don't think it should affect that much, here is the profile code anyway: `0190d0ab-72d1-98b9-1921-42f81df2c9e5`
Also, after the recent update (1.1.11) key spawning seems to be back to normal.

**Comment by broken-usb** [comment]
Here is another log file where the bug happens again multiple times:
[LogOutput.log](https://github.com/user-attachments/files/16432802/LogOutput.log)

**Comment by mattymatty97** [comment]
> [Debug  :Matty's Fixes] Comedy new offset is 85

you sure you do not have set it up in the manualOffsets?

**Comment by broken-usb** [comment]
> > [Debug  :Matty's Fixes] Comedy new offset is 85
> 
> you sure you do not have set it up in the manualOffsets?

They were set to the default values:
![image](https://github.com/user-attachments/assets/758fd6d1-d004-46e2-ad0f-47f257fe21e7)
Not sure why it increased to 85

**Comment by broken-usb** [comment]
I went and dowloaded [Imperium](https://thunderstore.io/c/lethal-company/p/giosuel/Imperium/) so that i could more easily record the bug happening:

https://github.com/user-attachments/assets/6ace4512-e9d6-422c-892b-0202668a5996

Also ended up finding out that putting the masks on the Cupboard makes them "vanish", i forgot to show it in the video but they still count as collect since their value will contribute to stuff like ShipLoot, the dropped ones that fly out of the ship don't seem to count tho.

If you want to see if you replicate the bug here is the profile code: `01910590-9446-ff81-c9a7-aa7f94708c13` (Note that i only installed BetterSaves so i wouldn't accidentally mess with my already existing save files, the bug will happen both with and without it anyway).

**Comment by broken-usb** [comment]
Log file from my testing (forgot to upload it):
[LogOutput.log](https://github.com/user-attachments/files/16433751/LogOutput.log)

**Comment by mattymatty97** [comment]
do you have a language where the decimal separator is comma (`,`)  instead of dot (`.`)?

**Comment by broken-usb** [comment]
yes, my pc is set to Brazilian Portuguese

**Comment by mattymatty97** [comment]
haha, then for your computer 0.0085 is 85!

i guessed that was the issue and the new update should in theory parse the values using the InvariantCulture.. if that does not work i'll have to ask you to set your language temporaneally to one with `.` as decimal separator

also next release removes the default values for the masks as the new vertical calculation should work with them

**Comment by broken-usb** [comment]
> i guessed that was the issue and the new update should in theory parse the values using the InvariantCulture.. if that does not work i'll have to ask you to set your language temporaneally to one with `.` as decimal separator

Tested a bit and seems to be working as intended now after the recent update(1.1.14), no more masks flying into outer space.
