### ISSUE TITLE
[Incompatability] Motion Tracker in ItemClipping.Rotations is partially broken

### ISSUE THREAD

**Issue by dopadream** [mattymatty97/LTC_MattyFixes#22]
Hi, when launching this mod for the first time with [this](https://thunderstore.io/c/lethal-company/p/Entity378/Motion_Tracker_V2/) mod, you're able to edit the offsets for the rotations just fine, and they apply in game. For some reason, when you save these settings and re-launch the game, it deletes itself from the list somehow and you're no longer able to set any rotation for this specific item. It only happens with this one, as far as I know.

**Comment by mattymatty97** [comment]
please fill the new bug template, sadly i need more informations
