### ISSUE TITLE
[Request] Experimental: Restore limitless item clipping vertical offset

### ISSUE THREAD

**Issue by MathiusXII** [mattymatty97/LTC_MattyFixes#24]
For item clipping, I have the vertical offset set to -0.025, which looks good for many of the items in my opinion, and then I add all the others that don't look good to the manual offsets section. The experimental version has a restriction on the vertical offset that excludes negatives, while the regular version doesn't. I'd like to use the features in the experimental version, but I really don't want to since I'd have to add every item in the game to the manual offsets section and just set most of them to -0.025.

Could you remove this restriction please?

**Comment by mattymatty97** [comment]
the experimental builds use a different system to handle vertical offsets ( manualOffset will still override it )
so the VerticalOffset config has changed meaning and any value lower than the specified min will 100% make items sink in the ground. i can give you that option back but mean you'll consistently loose all your items on rehost

**Comment by MathiusXII** [comment]
But with experimental, having vertical offset set at 0 still makes items float a noticeable bit above the ground.

Are you referring to the funny behavior where the item is sunk down extra when it generates in a dungeon vs when it's dropped?

**Comment by mattymatty97** [comment]
there are two VerticalOffset configs. i was thinking about the OutOfBounds one. sorry.

i've extended the valid range for the ItemClipping one. now it's from -0.5 to 0.5.

will be in the next TS update

**Comment by MathiusXII** [comment]
Thanks matty
