### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by viiuan** [mattymatty97/LTC_MattyFixes#25]
I see the package has been marked as deprecated- is this a temporary thing or will the official package remain unsupported? Is the experimental package also unsupported?

**Comment by mattymatty97** [comment]
main package has been deprecate because i dropped support for it after v50.
Experimental package is a full rewrite and currently maintained updated. once i'm sure the Experimental package is stable i will re-upload it to the main Page ( un-Deprecating it )

**Comment by viiuan** [comment]
gotcha! thanks for the response :]
