### ISSUE TITLE
Floating Belt Bag

### ISSUE THREAD

**Issue by broken-usb** [mattymatty97/LTC_MattyFixes#27]
**Describe the bug**
Since update v1.1.26 the Belt Bag now floats a little when dropped.

**To Reproduce**
1. Buy a Belt Bag
2. Drop the Belt Bag
3. Look at it

**Screenshots**
![1966720_20241009095632_1](https://github.com/user-attachments/assets/933fd2f5-f6ad-43ee-9614-d6e0d5edc863)
![1966720_20241009095612_1](https://github.com/user-attachments/assets/09eb865e-fb1b-4824-8a54-6db9173e2054)

**Versions:**
 - Game: [v64]
 - Mod: [v1.1.26 - Current]
 - Experimental: [yes]

**Logs**
[LogOutput.log](https://github.com/user-attachments/files/17308617/LogOutput.log)

**Additional context**
I know i have [GeneralImprovements](https://thunderstore.io/c/lethal-company/p/ShaosilGaming/GeneralImprovements/) and [SmartItemSaving](https://thunderstore.io/c/lethal-company/p/SylviBlossom/SmartItemSaving/) installed but i have disabled their incompatible options:
![{9AD44164-9945-4221-9724-D876EC68620D}](https://github.com/user-attachments/assets/84865d4a-d2d3-4ab4-b80e-de3cb55c1819)
![{CE070229-FBBB-4EB0-BD75-0A9188F5A0CC}](https://github.com/user-attachments/assets/a31f653d-bd4c-4c82-9140-9735035999c5)
Also, here is the profile code: `01927161-000a-413a-66fc-515d5de58efa`

**Comment by mattymatty97** [comment]
this has now been confirmed to be fixed
