### ISSUE TITLE
The combination of GeneralImprovements and Matty Fixes can cause the sinking of spacecraft items

### ISSUE THREAD

**Issue by 1450143535** [mattymatty97/LTC_MattyFixes#29]
Based on my observation, I found that when these two modules are together, when I disconnect them and save them again, some of the items placed on the spaceship will sink to the floor of the spaceship. If it is a waist bag, it will disappear under the spaceship. When I only have Matty Fixes, this situation will not occur. Can you check if these two are incompatible and may cause this situation to occur

**Comment by 1450143535** [comment]
![Lethal Company Screenshot 2024 12 16 - 22 48 53 05](https://github.com/user-attachments/assets/3aaf4ec1-f337-4dad-be89-21bb5f6c9268)
![Lethal Company Screenshot 2024 12 16 - 22 49 01 64](https://github.com/user-attachments/assets/a1a2e07b-593a-483e-9091-8e957059fcda)

**Comment by mattymatty97** [comment]
this is a known incompatibility that's on GI side.. their `FixItemsFallingThrough` disables gravity of all items entirely while MattyFixes relies on having the items fall naturally

**Comment by 1450143535** [comment]
So is there a solution that can make the two compatible? I like the repair of sunken storage cabinet items in the MattyFixes mod, but this repair is lacking in the Generallmprovements
mod. The combination of the two seems to improve the gaming experience. Can you consider this suggestion in the future

**Comment by mattymatty97** [comment]
disable `FixItemsFallingThrough` on GI. and maybe head out to the LethalCompanyModding discord where people compiled lists of the incompatible settings and what to toggle on each side.

https://discord.com/channels/1168655651455639582/1211989201793449994

**Comment by 1450143535** [comment]
Thank you for providing the website. I have tried to access the website multiple times, but as I entered it from China, it seems that due to some force majeure factors, I am unable to view the solutions related to the website you provided. Do you have any other methods to provide me with solutions for incompatibility? I would greatly appreciate it
![屏幕截图 2024-12-22 234910](https://github.com/user-attachments/assets/7d2d86ac-dc36-45e6-b599-6526e66102d8)

**Comment by 1450143535** [comment]
And it seems that I don't have permission to access the website. What should I do?
![屏幕截图 2024-12-22 235618](https://github.com/user-attachments/assets/a0e39835-8ad2-48d0-b948-f2a4ae165683)
