### ISSUE TITLE
[Feedback] add a standalone patch, to fix monitor issues

### ISSUE THREAD

**Issue by CoolLKKPS** [mattymatty97/LTC_MattyFixes#5]
uh so, about monitor issues
- we already know "will cause slot change in the monitor if active radar booster, player 1 will changed to player 4, player 2 changed to player 1, player 4 changed to player 2, only those 3 players will be affect"
- if activate the radar, late joiners may will use 1 player slot plus additional 4 player slots, maybe cause by slot de-sync
- if late joiners taking slot 2 or slot 4 that previous used by other disconnected player, will cause slot de-sync

we know how that bugs work, so that's what we can do:
- prevent radar picking up (for clients) and activate (for host) when in orbit
- automatic deactivate the radar When radar are in the ship
- skip slot 2 and slot 4 for late joiners even slot 2 and slot 4 is empty

**Comment by CoolLKKPS** [comment]
@mattymatty97

**Comment by CoolLKKPS** [comment]
and about namefix patch, pretty sure don't need that if already have host fixes mod, the name should match the steam ID, and host fixes already done that

**Comment by CoolLKKPS** [comment]
ok actually namefix are pretty not useful, i don't think that can fix anything
and i did late joined a lobby, and cause slot de-sync, i cannot see a person who using the same slot with me, he will use "player \#7" name or similar like that, i don't think that's name issues, that's slot issues

**Comment by mattymatty97** [comment]
NameFixes is experimental and works by running a callback when steam finally has the correct username and then updating the display name of a player

additionally everytime the callback is triggered this mod will loop through all the radarIcons and attempt to find their associated PlayerController ( using the transform and not their index ) to use the right name

**Comment by CoolLKKPS** [comment]
uh just let u know, im still testing...
