### ISSUE TITLE
[README Enchancement/Suggestion] Add a list of all fixes

### ISSUE THREAD

**Issue by CatsArmy** [mattymatty97/LTC_MattyFixes#6]
Add a list of all/most mods that you will not need when using this mod: eg namefix(the reason also for why i am asking for this saw the latest commit). this list doesnt have to have all mods but even just having all features/fixes helps figure out what mods you would not need to install

**Comment by mattymatty97** [comment]
i'm quite sure all the fixes are correctly listed in the README.md? which one am i missing?
