### ISSUE TITLE
[Bug] ItemClippingFix LethalThings items floating high off the ground

### ISSUE THREAD

**Issue by MathiusXII** [mattymatty97/LTC_MattyFixes#7]
Seems to be a conflict with something else. I tested with just these mods and a few testing mods and it worked correctly.

Want the code for my modpack where it happens?

**Comment by mattymatty97** [comment]
some mods, are known to cause interference in the offset calculation for their items.
sadly the only solution is to list said items in the manualOverride config. typically with offset 0 or less than 1 unit if you want to tweak it a bit from the original

**Comment by MathiusXII** [comment]
Oh ok I didn't know there was a manual override. Thanks

**Comment by mattymatty97** [comment]
yeah, i'm sorry that. the solution is manual. but i did try various ways of dealing with it and there was always a mod that would break
